//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AftersalesPm_ValidationReport
    {
        public long Id { get; set; }
        public Nullable<long> IssueVerificationId { get; set; }
        public string ModelName { get; set; }
        public string SoftwareVersionName { get; set; }
        public Nullable<int> SoftwareVersionNo { get; set; }
        public string IssueDetails { get; set; }
        public string IssueOrRequirement { get; set; }
        public Nullable<int> NumberOfMpHsCheck { get; set; }
        public string FoundInGoldenHs { get; set; }
        public string FoundInMpHs { get; set; }
        public string ValidationResult { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public Nullable<long> Added { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> Updated { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
