//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AftersalesPm_FocIncentive
    {
        public long Id { get; set; }
        public Nullable<long> CreateFocId { get; set; }
        public Nullable<long> AsmUserId { get; set; }
        public string EmployeeCode { get; set; }
        public Nullable<long> ProjectId { get; set; }
        public string ProjectName { get; set; }
        public string SpareName { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string IncentiveRemarks { get; set; }
        public Nullable<decimal> FinalAmountForHead { get; set; }
        public Nullable<decimal> FinalAmountForOthers { get; set; }
        public Nullable<decimal> DeductionAmount { get; set; }
        public string D_Remarks { get; set; }
        public string Month { get; set; }
        public Nullable<int> MonNum { get; set; }
        public Nullable<long> Year { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> Added { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> Updated { get; set; }
    }
}
