//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AftersalesPm_IssueVerification
    {
        public long Id { get; set; }
        public Nullable<long> ProjectMasterId { get; set; }
        public string ModelName { get; set; }
        public string SoftwareVersionName { get; set; }
        public Nullable<int> SoftwareVersionNo { get; set; }
        public string Module { get; set; }
        public string IssueDetails { get; set; }
        public string IssueFrequency { get; set; }
        public string IssueType { get; set; }
        public string TestingPath { get; set; }
        public string ResultFound { get; set; }
        public string ExpectedResult { get; set; }
        public Nullable<int> NumberOfHSsChecked { get; set; }
        public string HSsIssueRatio { get; set; }
        public Nullable<int> ComplainPercentage { get; set; }
        public Nullable<int> NumberOfHSsReturn { get; set; }
        public string IssueSolvingInfo { get; set; }
        public Nullable<int> NumberOfSample { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string SupportingDocument { get; set; }
        public string DocumentUploadedByQc { get; set; }
        public Nullable<long> Added { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> Updated { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
