//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllTrialInfo
    {
        public long Id { get; set; }
        public Nullable<long> PlanId { get; set; }
        public Nullable<long> SmtTrialId { get; set; }
        public Nullable<long> HousingTrialId { get; set; }
        public Nullable<long> BatteryTrialId { get; set; }
        public Nullable<long> AssemblyTrialId { get; set; }
        public Nullable<System.DateTime> WorkingDate { get; set; }
        public Nullable<long> TrialPerDayCapacity { get; set; }
        public Nullable<long> TrialLineCapacity { get; set; }
        public Nullable<long> TrialLineAvailableCapacity { get; set; }
        public Nullable<long> TrialTotalQuantity { get; set; }
        public Nullable<long> LineInformation_Id { get; set; }
        public string TrialLineNumber { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> Added { get; set; }
    }
}
