//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationForNoc
    {
        public int ApplicationNocId { get; set; }
        public string ModelNo { get; set; }
        public string ApplicationDate { get; set; }
        public string UnitValue { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string MRP { get; set; }
        public string Multiplier { get; set; }
    }
}
