//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatteryAssemblyLineCapacityDetail
    {
        public long Id { get; set; }
        public Nullable<long> PlanId { get; set; }
        public Nullable<long> BatteryAssemblyId { get; set; }
        public Nullable<System.DateTime> WorkingDate { get; set; }
        public Nullable<long> PerDayCapacity { get; set; }
        public Nullable<long> LineCapacity { get; set; }
        public Nullable<long> LineAvailableCapacity { get; set; }
        public Nullable<long> Production { get; set; }
        public Nullable<long> TotalQuantityBAssembly { get; set; }
        public Nullable<long> LineInformation_Id { get; set; }
        public string LineNumber { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> Added { get; set; }
    
        public virtual BatteryAssemblyAndPacking BatteryAssemblyAndPacking { get; set; }
    }
}
