//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatteryAssemblyAndPacking
    {
        public BatteryAssemblyAndPacking()
        {
            this.BatteryAssemblyLineCapacityDetails = new HashSet<BatteryAssemblyLineCapacityDetail>();
        }
    
        public long Id { get; set; }
        public long PlanId { get; set; }
        public Nullable<long> ProjectId { get; set; }
        public string ProjectName { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public string PoCategory { get; set; }
        public Nullable<System.DateTime> MaterialReceiveStartDateBAssembly { get; set; }
        public Nullable<System.DateTime> MaterialReceiveEndDateBAssembly { get; set; }
        public Nullable<System.DateTime> IqcCompleteStartDateBAssembly { get; set; }
        public Nullable<System.DateTime> IqcCompleteEndDateBAssembly { get; set; }
        public Nullable<System.DateTime> TrialProductionStartDateBAssembly { get; set; }
        public Nullable<System.DateTime> TrialProductionEndDateBAssembly { get; set; }
        public Nullable<System.DateTime> SoftwareConfirmationStartDateBAssembly { get; set; }
        public Nullable<System.DateTime> SoftwareConfirmationEndDateBAssembly { get; set; }
        public Nullable<System.DateTime> RandDConfirmationStartDateBAssembly { get; set; }
        public Nullable<System.DateTime> RandDConfirmationEndDateBAssembly { get; set; }
        public Nullable<System.DateTime> AssemblyMassProductionStartDateBAssembly { get; set; }
        public Nullable<long> TotalQuantityBAssembly { get; set; }
        public Nullable<System.DateTime> AssemblyMassProductionEndDateBAssembly { get; set; }
        public Nullable<System.DateTime> PackingMassProductionStartDateBAssembly { get; set; }
        public Nullable<long> TotalQuantityBPacking { get; set; }
        public Nullable<System.DateTime> PackingMassProductionEndDateBAssembly { get; set; }
        public string StatusAssembAndPack { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<long> Added { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> Updated { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ICollection<BatteryAssemblyLineCapacityDetail> BatteryAssemblyLineCapacityDetails { get; set; }
    }
}
