//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Battery
    {
        public long Id { get; set; }
        public long PlanId { get; set; }
        public Nullable<long> ProjectId { get; set; }
        public string ProjectName { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public string PoCategory { get; set; }
        public Nullable<System.DateTime> MaterialReceiveStartDateBattery { get; set; }
        public Nullable<System.DateTime> MaterialReceiveEndDateBattery { get; set; }
        public Nullable<System.DateTime> IqcCompleteStartDateBattery { get; set; }
        public Nullable<System.DateTime> IqcCompleteEndDateBattery { get; set; }
        public Nullable<System.DateTime> TrialProductionStartDateBattery { get; set; }
        public Nullable<System.DateTime> TrialProductionEndDateBattery { get; set; }
        public Nullable<System.DateTime> BatteryReliabilityTestStartDate { get; set; }
        public Nullable<System.DateTime> BatteryReliabilityTestEndDate { get; set; }
        public Nullable<System.DateTime> BatteryMassProductionStartDate { get; set; }
        public Nullable<long> TotalQuantityBattery { get; set; }
        public Nullable<System.DateTime> BatteryMassProductionEndDate { get; set; }
        public Nullable<System.DateTime> BatteryAgingTestStartDate { get; set; }
        public Nullable<System.DateTime> BatteryAgingTestEndDate { get; set; }
        public string StatusBattery { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<long> Added { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> Updated { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
