//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatterySMT
    {
        public BatterySMT()
        {
            this.BatterySMTLineCapacityDetails = new HashSet<BatterySMTLineCapacityDetail>();
        }
    
        public long Id { get; set; }
        public long PlanId { get; set; }
        public Nullable<long> ProjectId { get; set; }
        public string ProjectName { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public string PoCategory { get; set; }
        public Nullable<System.DateTime> MaterialReceiveStartDateBSmt { get; set; }
        public Nullable<System.DateTime> MaterialReceiveEndDateBSmt { get; set; }
        public Nullable<System.DateTime> IqcCompleteStartDateBSmt { get; set; }
        public Nullable<System.DateTime> IqcCompleteEndDateBSmt { get; set; }
        public Nullable<System.DateTime> TrialProductionStartDateBSmt { get; set; }
        public Nullable<System.DateTime> TrialProductionEndDateBSmt { get; set; }
        public Nullable<System.DateTime> SmtMassProductionStartDateBSmt { get; set; }
        public Nullable<long> TotalQuantityBSmt { get; set; }
        public Nullable<System.DateTime> SmtMassProductionEndDateBSmt { get; set; }
        public string StatusBSmt { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<long> Added { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> Updated { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ICollection<BatterySMTLineCapacityDetail> BatterySMTLineCapacityDetails { get; set; }
    }
}
