//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BdIqcBomPassRecord
    {
        public long Id { get; set; }
        public Nullable<long> VariantId { get; set; }
        public Nullable<long> ProjectId { get; set; }
        public Nullable<long> BomId { get; set; }
        public string Description { get; set; }
        public string SpareDescription { get; set; }
        public string BOMType { get; set; }
        public string BomQuantity { get; set; }
        public string BomPassedQuantity { get; set; }
        public string BomFailQuantity { get; set; }
        public string Remarks { get; set; }
        public Nullable<long> AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
