//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOM
    {
        public long Id { get; set; }
        public Nullable<long> BomProductModelId { get; set; }
        public string InventoryItemId { get; set; }
        public string InventoryItemCode { get; set; }
        public string ItemName { get; set; }
        public string Description { get; set; }
        public string Component { get; set; }
        public Nullable<decimal> RequiredPerUnit { get; set; }
        public string SpareItemCode { get; set; }
        public string SpareDescription { get; set; }
        public string ItemType { get; set; }
        public string AssemblyCode { get; set; }
        public string Company { get; set; }
        public string Uom { get; set; }
        public string ProductType { get; set; }
        public string Color { get; set; }
        public string BOMType { get; set; }
        public Nullable<decimal> ItemCost { get; set; }
        public string BomVersion { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string AddedBy { get; set; }
    
        public virtual BomProductModel BomProductModel { get; set; }
    }
}
