//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BTRCIMEIRegistration
    {
        public long ID { get; set; }
        public long BTRCModelId { get; set; }
        public string ProjectModel { get; set; }
        public string IMEITac1 { get; set; }
        public string IMEITac2 { get; set; }
        public string IMEITac3 { get; set; }
        public string IMEITac4 { get; set; }
        public string IMEI1 { get; set; }
        public string IMEI2 { get; set; }
        public string IMEI3 { get; set; }
        public string IMEI4 { get; set; }
        public Nullable<long> Added { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> Updated { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> Exported { get; set; }
    
        public virtual BTRCModel BTRCModel { get; set; }
    }
}
