//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BTRCModel
    {
        public BTRCModel()
        {
            this.BTRCIMEIRegistrations = new HashSet<BTRCIMEIRegistration>();
        }
    
        public long ModelID { get; set; }
        public string Brand { get; set; }
        public long ProjectMasterId { get; set; }
        public string ProjectName { get; set; }
        public string ProjectModel { get; set; }
        public string MarketingName { get; set; }
        public string Color { get; set; }
        public string DeviceType { get; set; }
        public string ApplicationRef { get; set; }
        public string ContryOfOrigin { get; set; }
        public Nullable<long> SupplierId { get; set; }
        public string Manufacturer { get; set; }
        public Nullable<int> SimSlotNumber { get; set; }
        public string BatteryRating { get; set; }
        public string BatteryCapacityTested { get; set; }
        public string ChargerAdapterType { get; set; }
        public string ChargerRating { get; set; }
        public string ProcessorName { get; set; }
        public string Ram { get; set; }
        public string Rom { get; set; }
        public string NFC { get; set; }
        public string Bluetooth { get; set; }
        public string WLAN { get; set; }
        public string DataSpeed { get; set; }
        public string SARValue { get; set; }
        public string FrontCamera { get; set; }
        public string BackCamera { get; set; }
        public string CameraResulution { get; set; }
        public string RadioInterface { get; set; }
        public string SecondGen { get; set; }
        public string ThirdGen { get; set; }
        public string FourthGen { get; set; }
        public string Motherboard { get; set; }
        public string ChipsetName { get; set; }
        public string OSName { get; set; }
        public string ShipmentMode { get; set; }
        public string SourcingType { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> PriceBDT { get; set; }
        public string MarketingPeriod { get; set; }
        public string SerialNo { get; set; }
        public Nullable<long> Added { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> Updated { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> Exported { get; set; }
    
        public virtual ICollection<BTRCIMEIRegistration> BTRCIMEIRegistrations { get; set; }
    }
}
