//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChargerHousing
    {
        public long Id { get; set; }
        public Nullable<long> ProjectId { get; set; }
        public long PlanId { get; set; }
        public string ProjectName { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public string PoCategory { get; set; }
        public Nullable<System.DateTime> MaterialReceiveStartDate { get; set; }
        public Nullable<System.DateTime> MaterialReceiveEndDate { get; set; }
        public Nullable<System.DateTime> IqcCompleteStartDate { get; set; }
        public Nullable<System.DateTime> IqcCompleteEndDate { get; set; }
        public Nullable<System.DateTime> TrialProductionStartDate { get; set; }
        public Nullable<System.DateTime> TrialProductionEndDate { get; set; }
        public Nullable<System.DateTime> HousingReliabilityTestStartDate { get; set; }
        public Nullable<System.DateTime> HousingReliabilityTestEndDate { get; set; }
        public Nullable<System.DateTime> HousingMassProductionStartDate { get; set; }
        public Nullable<long> TotalQuantity { get; set; }
        public Nullable<System.DateTime> HousingMassProductionEndDate { get; set; }
        public string Status { get; set; }
        public Nullable<long> Added { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> Updated { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
