//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cm_RefundProjectAmount
    {
        public long Id { get; set; }
        public Nullable<long> ProjectMasterId { get; set; }
        public string ProjectModel { get; set; }
        public string ProjectType { get; set; }
        public string ShipmentType { get; set; }
        public string SourcingType { get; set; }
        public string Orders { get; set; }
        public Nullable<System.DateTime> PoDate { get; set; }
        public Nullable<System.DateTime> WarehouseEntryDate { get; set; }
        public Nullable<int> DaysDiff { get; set; }
        public Nullable<int> EffectiveDays { get; set; }
        public Nullable<long> DeductPoint { get; set; }
        public Nullable<long> DaysDiffForDeduct { get; set; }
        public Nullable<long> DeductedAmount { get; set; }
        public string IsRefund { get; set; }
        public Nullable<long> RefundAmount { get; set; }
        public Nullable<int> RefundPercentage { get; set; }
        public Nullable<System.DateTime> EffectiveMonth { get; set; }
        public string ProjectSourchingType { get; set; }
        public string RoleName { get; set; }
        public string Month { get; set; }
        public Nullable<int> MonNum { get; set; }
        public Nullable<long> Year { get; set; }
        public Nullable<long> Added { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> Updated { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
