//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CmnUser
    {
        public CmnUser()
        {
            this.Posts = new HashSet<Post>();
        }
    
        public long CmnUserId { get; set; }
        public string UserFullName { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string MobileNumber { get; set; }
        public string Email { get; set; }
        public string ProfilePictureUrl { get; set; }
        public string Designation { get; set; }
        public string EmployeeCode { get; set; }
        public bool IsActive { get; set; }
        public string RoleName { get; set; }
        public Nullable<long> AssignBy { get; set; }
        public Nullable<System.DateTime> AssignDate { get; set; }
        public Nullable<System.DateTime> AssignStartDate { get; set; }
        public Nullable<System.DateTime> AssignEndDate { get; set; }
        public string AssignRoles { get; set; }
        public string Department { get; set; }
        public string Section { get; set; }
        public Nullable<System.DateTime> DateOfJoining { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> ServiceLength { get; set; }
        public Nullable<long> Added { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> Updated { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string ExtendedRoleName { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string LastLoginDateTime { get; set; }
        public Nullable<bool> IsRememberMailSend { get; set; }
        public string LastLoginIpAddress { get; set; }
        public Nullable<System.DateTime> LastPasswordUpdateDate { get; set; }
    
        public virtual ICollection<Post> Posts { get; set; }
    }
}
