//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommonIssue
    {
        public long CommonIssueId { get; set; }
        public long ProjectMasterId { get; set; }
        public string IssueTitle { get; set; }
        public string Component { get; set; }
        public string Description { get; set; }
        public long CreatorUserId { get; set; }
        public string CreatorUserRole { get; set; }
        public Nullable<long> SolverUserId { get; set; }
        public string SolverUserRole { get; set; }
        public string CurrentlyWorkingRole { get; set; }
        public string ReferenceFlow { get; set; }
        public Nullable<int> NoOfTimesRefered { get; set; }
        public string ReferenceRemarks { get; set; }
        public Nullable<bool> IsIgnored { get; set; }
        public Nullable<long> IgnoredBy { get; set; }
        public string SolutionComment { get; set; }
        public string IgnoreComment { get; set; }
        public bool IsSolved { get; set; }
        public Nullable<long> Added { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> Updated { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
