//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostMasterDetail
    {
        public long Id { get; set; }
        public Nullable<long> CostMasterId { get; set; }
        public string MSRP { get; set; }
        public string Invoice { get; set; }
        public string Rebate { get; set; }
        public string InvoiceAfterRebate { get; set; }
        public string COGS { get; set; }
        public string GP { get; set; }
        public string MSRP_IP_Percent { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string AddedBy { get; set; }
    
        public virtual CostMaster CostMaster { get; set; }
    }
}
