//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostMaster
    {
        public CostMaster()
        {
            this.CostMasterDetails = new HashSet<CostMasterDetail>();
            this.CostMasterEmailLogs = new HashSet<CostMasterEmailLog>();
            this.CostProposals = new HashSet<CostProposal>();
            this.CostSimulationLogs = new HashSet<CostSimulationLog>();
        }
    
        public long Id { get; set; }
        public long CostManagementModelId { get; set; }
        public string ModelName { get; set; }
        public string PhaseNo { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public string ManagementProposal { get; set; }
        public System.DateTime AddedDate { get; set; }
        public long AddedBy { get; set; }
        public string AddedFrom { get; set; }
        public string COGS { get; set; }
        public string FinalMSRP { get; set; }
        public string FinalInvoice { get; set; }
        public string FinalGp { get; set; }
    
        public virtual CostManagementModel CostManagementModel { get; set; }
        public virtual ICollection<CostMasterDetail> CostMasterDetails { get; set; }
        public virtual ICollection<CostMasterEmailLog> CostMasterEmailLogs { get; set; }
        public virtual ICollection<CostProposal> CostProposals { get; set; }
        public virtual ICollection<CostSimulationLog> CostSimulationLogs { get; set; }
    }
}
