//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostManagementModel
    {
        public CostManagementModel()
        {
            this.CostMasters = new HashSet<CostMaster>();
        }
    
        public long Id { get; set; }
        public long OrderQuantityDetailsId { get; set; }
        public bool IsCalculated { get; set; }
        public System.DateTime AddedDate { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual ICollection<CostMaster> CostMasters { get; set; }
    }
}
