//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostMasterEmailLog
    {
        public long Id { get; set; }
        public long CostMasterId { get; set; }
        public string EmailAddress { get; set; }
        public string EmailBody { get; set; }
        public Nullable<bool> IsEmailSent { get; set; }
        public Nullable<System.DateTime> DeliveryTime { get; set; }
    
        public virtual CostMaster CostMaster { get; set; }
    }
}
