//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreateFocForAftersalesPm
    {
        public long Id { get; set; }
        public Nullable<long> ProjectId { get; set; }
        public string ProjectName { get; set; }
        public string SpareName { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public Nullable<System.DateTime> PoDate { get; set; }
        public string PoCategory { get; set; }
        public string EmployeeCode { get; set; }
        public Nullable<long> AsmUserId { get; set; }
        public string Supplier { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> FocConfirmedDate { get; set; }
        public Nullable<System.DateTime> InventoryEntryDate { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<long> Quantity { get; set; }
        public Nullable<long> ShipmentQuantity { get; set; }
        public string Month { get; set; }
        public Nullable<int> MonNum { get; set; }
        public Nullable<long> Year { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> Added { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> Updated { get; set; }
    }
}
