//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyProductionCapacity
    {
        public long ID { get; set; }
        public string CellPhoneType { get; set; }
        public Nullable<int> DailyCapacity { get; set; }
    }
}
