//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DispatchToMarketRemainingStock
    {
        public long DispatchToMarketStockId { get; set; }
        public string Model { get; set; }
        public long TotalMarketDispatch { get; set; }
        public long TotalMarketSell { get; set; }
        public Nullable<long> TotalUnActive { get; set; }
        public long RemainingMarketStock { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<long> StockAfterApplyMOE { get; set; }
        public Nullable<decimal> AppliedMOE { get; set; }
    }
}
