//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public long Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Thread { get; set; }
        public string LogLevel { get; set; }
        public string Source { get; set; }
        public string LogMessage { get; set; }
        public string Exception { get; set; }
    }
}
