//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeatureSpecFromApi
    {
        public long Id { get; set; }
        public string RelevantWaltonModel { get; set; }
        public string Brand { get; set; }
        public string ModelName { get; set; }
        public string DisplaySize { get; set; }
        public string Camera { get; set; }
        public string TorchLight { get; set; }
        public string FmRadio { get; set; }
        public string OperatingSyatem { get; set; }
        public string BuiltInFacebook { get; set; }
        public string FixedMemory { get; set; }
        public string Sound { get; set; }
        public string Phonebook { get; set; }
        public string ExpandableMemory { get; set; }
        public string Battery { get; set; }
        public string Color { get; set; }
        public string MrpPrice { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Password { get; set; }
        public string DpPrice { get; set; }
        public string RpPrice { get; set; }
        public string BackMargin { get; set; }
        public string Multimedia { get; set; }
        public string Others { get; set; }
        public string Resolution { get; set; }
        public string Network { get; set; }
    }
}
