//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FocClaim
    {
        public long Id { get; set; }
        public Nullable<long> ProjectMasterId { get; set; }
        public Nullable<long> OrderQuantityDetailId { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public Nullable<long> OrderQuantity { get; set; }
        public Nullable<long> BomProductModelId { get; set; }
        public string BomProductModel { get; set; }
        public string BomType { get; set; }
        public Nullable<long> BomId { get; set; }
        public string Description { get; set; }
        public string SpareDescription { get; set; }
        public string ClaimQuantity { get; set; }
        public Nullable<long> ClaimedBy { get; set; }
        public Nullable<System.DateTime> ClaimDate { get; set; }
        public string ReceiveQuantity { get; set; }
        public Nullable<long> ReceivedBy { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
