//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForeignIqc
    {
        public long Id { get; set; }
        public Nullable<long> ProjectId { get; set; }
        public Nullable<long> VariantId { get; set; }
        public string LotNo { get; set; }
        public string LotQuantity { get; set; }
        public string ShipmentNo { get; set; }
        public string AllMaterialPassed { get; set; }
        public string NoOfInspectionTime { get; set; }
        public string ManagementApproved { get; set; }
        public Nullable<System.DateTime> ManagementApproveDate { get; set; }
        public string SupportingDoc { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> IqcStartDate { get; set; }
        public Nullable<System.DateTime> WarehouseReceiveDate { get; set; }
        public string SourcingApproved { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> AddedBy { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
