//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralIncident
    {
        public long GeneralIncidentId { get; set; }
        public string RefferedRole { get; set; }
        public string GeneralIncidentTitle { get; set; }
        public string GeneralIncidentCategories { get; set; }
        public string GeneralIncidentDetails { get; set; }
        public Nullable<long> AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpadatedDate { get; set; }
        public string IsValid { get; set; }
        public Nullable<System.DateTime> DiscloseDate { get; set; }
        public Nullable<long> DisclosedBy { get; set; }
        public string DiscloseRemark { get; set; }
        public Nullable<long> ReassignId { get; set; }
        public string ReassignRemark { get; set; }
        public Nullable<long> ReassignedBy { get; set; }
        public Nullable<System.DateTime> ReassignDate { get; set; }
        public string Status { get; set; }
        public string FileUploadPath { get; set; }
        public string ModelName { get; set; }
        public string Issues { get; set; }
        public Nullable<long> SubmittedBy { get; set; }
        public Nullable<System.DateTime> SubmittedDate { get; set; }
        public string SubmitRemark { get; set; }
    }
}
