//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralIncidentLog
    {
        public long LogId { get; set; }
        public Nullable<long> GeneralIncidentId { get; set; }
        public string RefferedRole { get; set; }
        public string GeneralIncidentTitle { get; set; }
        public string GeneralIncidentCategories { get; set; }
        public string GeneralIncidentDetails { get; set; }
        public Nullable<long> AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> UpadatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> ForwaredBy { get; set; }
        public Nullable<System.DateTime> ForwardedDate { get; set; }
        public string ForwardRemark { get; set; }
        public string Status { get; set; }
        public string FileUploadPath { get; set; }
        public string ModelName { get; set; }
        public string Issues { get; set; }
    }
}
