//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralIncidentAssign
    {
        public long AssignIncidentId { get; set; }
        public Nullable<long> GeneralIncidentId { get; set; }
        public string AssignRemarks { get; set; }
        public Nullable<long> AssignedBy { get; set; }
        public string AssignByRole { get; set; }
        public Nullable<System.DateTime> AssignDate { get; set; }
        public Nullable<long> AssignedTo { get; set; }
        public string AssignedToRole { get; set; }
        public string Status { get; set; }
    }
}
