//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HwEngineerAssign
    {
        public long HwEngineerAssignId { get; set; }
        public Nullable<long> HwTestInchargeAssignId { get; set; }
        public Nullable<long> ProjectMasterId { get; set; }
        public Nullable<long> HwTestMasterId { get; set; }
        public string HwTestName { get; set; }
        public string HwEngineerIds { get; set; }
        public string HwEngineerNames { get; set; }
        public string HwInchargeRemark { get; set; }
        public string Remark { get; set; }
        public string Result { get; set; }
        public Nullable<long> AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> SubmittedBy { get; set; }
        public Nullable<System.DateTime> SubmittedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Status { get; set; }
    }
}
