//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HwFgBatteryTestCondition
    {
        public HwFgBatteryTestCondition()
        {
            this.HwFgBatteryTestResults = new HashSet<HwFgBatteryTestResult>();
        }
    
        public long HwFgBatteryTestConditionId { get; set; }
        public long HwFgBatteryTestMasterId { get; set; }
        public long CycleNo { get; set; }
        public string TestCondition { get; set; }
        public string ChargeCurrent { get; set; }
        public string CutoffCurrent { get; set; }
        public string LimitedVoltage { get; set; }
        public string DischargeCurrent { get; set; }
        public string CutoffVoltage { get; set; }
        public string RestTimeAfter_Charge { get; set; }
        public string RestTimeAfter_Discharge { get; set; }
        public string QcDocUploadPath { get; set; }
        public Nullable<long> AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual HwFgBatteryTestMaster HwFgBatteryTestMaster { get; set; }
        public virtual ICollection<HwFgBatteryTestResult> HwFgBatteryTestResults { get; set; }
    }
}
