//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HwFgBatteryTestResult
    {
        public long HwFgBatteryTestResultId { get; set; }
        public long HwFgBatteryTestConditionId { get; set; }
        public long CycleNo { get; set; }
        public long ItemNo { get; set; }
        public string ItemName { get; set; }
        public string ChargingCapacity { get; set; }
        public string ChargingTime { get; set; }
        public string DischargingCapacity { get; set; }
        public string DischargingTime { get; set; }
        public Nullable<bool> Result { get; set; }
        public string QcDocUploadPath { get; set; }
        public Nullable<long> AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual HwFgBatteryTestCondition HwFgBatteryTestCondition { get; set; }
    }
}
