//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HwFgChargerTest
    {
        public HwFgChargerTest()
        {
            this.HwFgChargerDetails = new HashSet<HwFgChargerDetail>();
        }
    
        public long HwFgChargerTestId { get; set; }
        public long HwQcAssignId { get; set; }
        public Nullable<long> HwQcInchargeAssignId { get; set; }
        public Nullable<long> ProjectMasterId { get; set; }
        public string ChargerType { get; set; }
        public string InputSpec { get; set; }
        public string OutputSpec { get; set; }
        public string TestCondition { get; set; }
        public string CcModeTemperature { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> OverallTestResultStatus { get; set; }
        public string Recommendation { get; set; }
        public Nullable<long> PreparedBy { get; set; }
        public Nullable<long> CheckedBy { get; set; }
        public Nullable<long> ApprovedBy { get; set; }
        public string QcDocUploadPath { get; set; }
        public Nullable<long> AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ICollection<HwFgChargerDetail> HwFgChargerDetails { get; set; }
        public virtual HwQcAssign HwQcAssign { get; set; }
    }
}
