//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HwFgChargerDetail
    {
        public long HwFgChargerDetailId { get; set; }
        public long HwFgChargerTestId { get; set; }
        public string FloatingVoltage { get; set; }
        public string SetLoadOutPutVoltage_Ac180v { get; set; }
        public string SetLoadOutPutVoltage_Ac220v { get; set; }
        public string SetLoadOutPutVoltage_Ac240v { get; set; }
        public string SetLoadOutPutCurrent_Ac180v { get; set; }
        public string SetLoadOutPutCurrent_Ac220v { get; set; }
        public string SetLoadOutPutCurrent_Ac240v { get; set; }
        public string CurrentLeakage { get; set; }
        public string ShortProtection { get; set; }
        public string LoadRipple { get; set; }
        public string QcDocUploadPath { get; set; }
        public Nullable<long> AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual HwFgChargerTest HwFgChargerTest { get; set; }
    }
}
