//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HwFgUsbCableTest
    {
        public HwFgUsbCableTest()
        {
            this.HwFgUsbTestDetails = new HashSet<HwFgUsbTestDetail>();
        }
    
        public long HwFgUsbCableTestId { get; set; }
        public long HwQcAssignId { get; set; }
        public Nullable<long> HwQcInchargeAssignId { get; set; }
        public Nullable<long> ProjectMasterId { get; set; }
        public Nullable<bool> FinalResult { get; set; }
        public Nullable<long> AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> CheckedBy { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public string QcDocUploadPath { get; set; }
        public Nullable<long> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ICollection<HwFgUsbTestDetail> HwFgUsbTestDetails { get; set; }
    }
}
