//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HwFieldTestMaster
    {
        public long FieldTestMasterId { get; set; }
        public Nullable<long> ProjectMasterId { get; set; }
        public long HwQcInchargeAssignId { get; set; }
        public string Model { get; set; }
        public string BenchMarkPhone { get; set; }
        public string Route { get; set; }
        public string Region { get; set; }
        public string FrequencyBand { get; set; }
        public string Operator { get; set; }
        public string TestName { get; set; }
        public string TestCategory { get; set; }
        public string TestDuration { get; set; }
        public string TestFocus { get; set; }
        public string NumberOfCalls { get; set; }
        public Nullable<System.DateTime> TestDate { get; set; }
        public string FieldTestResult { get; set; }
        public string Remark { get; set; }
        public Nullable<long> AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
