//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HwFieldTest
    {
        public long FieldTestId { get; set; }
        public long FieldTestMasterId { get; set; }
        public string OperatorName { get; set; }
        public string Location { get; set; }
        public string SpeedLimit { get; set; }
        public string TestedRssiBars { get; set; }
        public string TestedCallDrop { get; set; }
        public string TestedShortMute { get; set; }
        public string TestedLongMute { get; set; }
        public string BechmarkRssiBars { get; set; }
        public string BenchmarkCallDrop { get; set; }
        public string BenchmarkShortMute { get; set; }
        public string BenchMarkLongMute { get; set; }
        public Nullable<long> AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
