//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HwInchargeIssue
    {
        public long HwInchargeIssuesId { get; set; }
        public Nullable<long> ProjectMasterId { get; set; }
        public Nullable<long> HwQcInchargeAssignId { get; set; }
        public string HwIssue { get; set; }
        public string HwIssueDetail { get; set; }
        public string CommercialDecision { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsReviewd { get; set; }
        public Nullable<long> AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
