//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HwInternalResistanceBatteryTest
    {
        public long HwInternalResistanceBatteryTestId { get; set; }
        public long HwBatteryTestId { get; set; }
        public string SampleBatteryOrCellWithNo { get; set; }
        public string TestValue { get; set; }
        public string Unit { get; set; }
        public string Result { get; set; }
        public string NTC { get; set; }
        public string AnnouncedCapacityAfterTest { get; set; }
        public string PhysicalConditionAfterTest { get; set; }
        public string CadexCycleTest { get; set; }
        public string LastDischargeCapacity { get; set; }
        public string Remarks { get; set; }
        public Nullable<long> Added { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> Updated { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
