//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HwIssueComment
    {
        public long HwIssueCommentId { get; set; }
        public long HwQcAssignId { get; set; }
        public long ProjectMasterId { get; set; }
        public string IssueName { get; set; }
        public string IssueTypeName { get; set; }
        public string IssueTypeDetailName { get; set; }
        public string IssueComment { get; set; }
        public System.DateTime IssueCommetDate { get; set; }
        public string VerifierComment { get; set; }
        public Nullable<long> VerifiedBy { get; set; }
        public string IssueStatus { get; set; }
        public string HwQcInchargeComment { get; set; }
        public Nullable<System.DateTime> HwQcInchargeCommentDate { get; set; }
        public string CommercialComment { get; set; }
        public Nullable<System.DateTime> CommercialCommentDate { get; set; }
        public Nullable<long> Added { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> Updated { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual HwQcAssign HwQcAssign { get; set; }
    }
}
