//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HwItemization
    {
        public long HwItemizationId { get; set; }
        public long ProjectMasterId { get; set; }
        public long HwQcInchargeAssignId { get; set; }
        public long HwQcAssignId { get; set; }
        public long ItemComponentId { get; set; }
        public string YesNot { get; set; }
        public Nullable<long> IcComponentNumberId { get; set; }
        public string IcComponent_Vendor { get; set; }
        public string Compatibility { get; set; }
        public string Type { get; set; }
        public string ExistingItem { get; set; }
        public string SupplierCode { get; set; }
        public string Remarks { get; set; }
        public Nullable<long> AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ProjectMaster ProjectMaster { get; set; }
    }
}
