//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HwQcAssign
    {
        public HwQcAssign()
        {
            this.HwFgBatteryTestMasters = new HashSet<HwFgBatteryTestMaster>();
            this.HwFgChargerTests = new HashSet<HwFgChargerTest>();
            this.HwIssueComments = new HashSet<HwIssueComment>();
            this.HwTestBatteryInfos = new HashSet<HwTestBatteryInfo>();
            this.HwTestCameraInfos = new HashSet<HwTestCameraInfo>();
            this.HwTestChargerInfos = new HashSet<HwTestChargerInfo>();
            this.HwTestChargingInfos = new HashSet<HwTestChargingInfo>();
            this.HwTestCrossMatchInfos = new HashSet<HwTestCrossMatchInfo>();
            this.HwTestEarphoneInterfaceInfos = new HashSet<HwTestEarphoneInterfaceInfo>();
            this.HwTestFPCandSIMSlotInfos = new HashSet<HwTestFPCandSIMSlotInfo>();
            this.HwTestHousingInfos = new HashSet<HwTestHousingInfo>();
            this.HwTestOverallResults = new HashSet<HwTestOverallResult>();
            this.HwTestPcbAs = new HashSet<HwTestPcbA>();
            this.HwTestPcbs = new HashSet<HwTestPcb>();
            this.HwTestSoundInfos = new HashSet<HwTestSoundInfo>();
            this.HwTestTpLcdInfos = new HashSet<HwTestTpLcdInfo>();
            this.HwTestUSBCableInfos = new HashSet<HwTestUSBCableInfo>();
        }
    
        public long HwQcAssignId { get; set; }
        public Nullable<long> ProjectMasterId { get; set; }
        public Nullable<long> HwAllTestId { get; set; }
        public long HwQcInchargeAssignId { get; set; }
        public long HwQcUserId { get; set; }
        public System.DateTime HwQcAssignDate { get; set; }
        public string QcDocUploadPath { get; set; }
        public Nullable<System.DateTime> HwDocUploadDate { get; set; }
        public Nullable<System.DateTime> QcSubmissionDate { get; set; }
        public Nullable<long> VerifiedBy { get; set; }
        public string VerifierName { get; set; }
        public Nullable<System.DateTime> VerificationDate { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DeadLineDate { get; set; }
        public Nullable<long> Added { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> Updated { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ICollection<HwFgBatteryTestMaster> HwFgBatteryTestMasters { get; set; }
        public virtual ICollection<HwFgChargerTest> HwFgChargerTests { get; set; }
        public virtual ICollection<HwIssueComment> HwIssueComments { get; set; }
        public virtual HwQcInchargeAssign HwQcInchargeAssign { get; set; }
        public virtual ICollection<HwTestBatteryInfo> HwTestBatteryInfos { get; set; }
        public virtual ICollection<HwTestCameraInfo> HwTestCameraInfos { get; set; }
        public virtual ICollection<HwTestChargerInfo> HwTestChargerInfos { get; set; }
        public virtual ICollection<HwTestChargingInfo> HwTestChargingInfos { get; set; }
        public virtual ICollection<HwTestCrossMatchInfo> HwTestCrossMatchInfos { get; set; }
        public virtual ICollection<HwTestEarphoneInterfaceInfo> HwTestEarphoneInterfaceInfos { get; set; }
        public virtual ICollection<HwTestFPCandSIMSlotInfo> HwTestFPCandSIMSlotInfos { get; set; }
        public virtual ICollection<HwTestHousingInfo> HwTestHousingInfos { get; set; }
        public virtual ICollection<HwTestOverallResult> HwTestOverallResults { get; set; }
        public virtual ICollection<HwTestPcbA> HwTestPcbAs { get; set; }
        public virtual ICollection<HwTestPcb> HwTestPcbs { get; set; }
        public virtual ICollection<HwTestSoundInfo> HwTestSoundInfos { get; set; }
        public virtual ICollection<HwTestTpLcdInfo> HwTestTpLcdInfos { get; set; }
        public virtual ICollection<HwTestUSBCableInfo> HwTestUSBCableInfos { get; set; }
    }
}
