//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HwRuOperatingHeatTest
    {
        public long HwRuOperatingHeatTestd { get; set; }
        public long HwQcAssignId { get; set; }
        public Nullable<long> TestCriterionNo { get; set; }
        public string TestCondition_Temperature { get; set; }
        public string TestCondition_Humidity { get; set; }
        public string TestCondition_BothSim { get; set; }
        public string TestCondition_Wifi { get; set; }
        public string TestCondition_Brightness { get; set; }
        public string TestCondition_Sound { get; set; }
        public string TestCondition_Charge { get; set; }
        public string TestConditionHdGame { get; set; }
        public string TestCondition_HdVideo { get; set; }
        public string TestDuration { get; set; }
        public string Result { get; set; }
        public string Judgement { get; set; }
        public string BarePcbCase { get; set; }
        public string FrontSidePicture { get; set; }
        public string BackSidePicture { get; set; }
        public string SideBcasingPicture { get; set; }
        public string Remarks { get; set; }
        public Nullable<long> Added { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> Updated { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
