//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HwRuDisplayElectricalOpticalTest
    {
        public long HwRuDisplayElectricalOpticalTestId { get; set; }
        public long HwQcAssignId { get; set; }
        public string SwVersion { get; set; }
        public string BrightnessLevel { get; set; }
        public string Topics { get; set; }
        public string OldSample { get; set; }
        public string NewSample { get; set; }
        public string TestCondition { get; set; }
        public string Remarks { get; set; }
        public Nullable<long> Added { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> Updated { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
