//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HwRuCameraTestMaster
    {
        public long HwRuCameraTestMasterId { get; set; }
        public long HwQcAssignId { get; set; }
        public string SwVersion { get; set; }
        public string FrontCam_Resoluton { get; set; }
        public string FrontCam_Sensor { get; set; }
        public string FrontCam_SensorSupplier { get; set; }
        public string FrontCam_PcbaNumber { get; set; }
        public string RearCam_Resolution { get; set; }
        public string RearCam_Sensor { get; set; }
        public string RearCam_SensorSupplier { get; set; }
        public string RearCam_PcbaNumber { get; set; }
        public string Remarks { get; set; }
        public Nullable<long> Added { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> Updated { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
