//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HwRuCameraTestDetail
    {
        public long HwRuCameraTestDetailId { get; set; }
        public long HwRuCameraTestMasterId { get; set; }
        public string TestCriteria { get; set; }
        public string RearCam_Result { get; set; }
        public string RearCam_Remarks { get; set; }
        public string FrontCam_Result { get; set; }
        public string FrontCam_Remarks { get; set; }
        public Nullable<long> Added { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> Updated { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
