//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HwTestAdditionalInfo
    {
        public long HwTestAdditionalInfoId { get; set; }
        public Nullable<long> HwEngineerAssignId { get; set; }
        public Nullable<long> HwTestMasterId { get; set; }
        public Nullable<long> HwTestInchargeAssignId { get; set; }
        public string FieldName { get; set; }
        public string FieldValue { get; set; }
        public Nullable<long> AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
    }
}
