//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HwTestInchargeAssign
    {
        public long HwTestInchargeAssignId { get; set; }
        public Nullable<long> HwTestMasterId { get; set; }
        public Nullable<long> ProjectMasterId { get; set; }
        public string ProjectName { get; set; }
        public string HwTestName { get; set; }
        public Nullable<long> AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public Nullable<long> ForwardedBy { get; set; }
        public Nullable<System.DateTime> ForwrdedDate { get; set; }
        public string ForwardRemarks { get; set; }
        public Nullable<long> Serial { get; set; }
    }
}
