//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incentive
    {
        public long Id { get; set; }
        public string UserId { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> ThisMonthAmount { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> TotalIncentive { get; set; }
        public Nullable<decimal> FixedIncentive { get; set; }
        public Nullable<double> Percentage { get; set; }
        public string Month { get; set; }
        public Nullable<int> MonNum { get; set; }
        public Nullable<long> AmountCarry { get; set; }
        public Nullable<decimal> AmountDeduction { get; set; }
        public string DeductionRemarks { get; set; }
        public Nullable<decimal> AddedAmount { get; set; }
        public Nullable<decimal> TotalReward { get; set; }
        public Nullable<decimal> Reward { get; set; }
        public Nullable<decimal> TotalPenalties { get; set; }
        public Nullable<decimal> Penalties { get; set; }
        public string Remarks { get; set; }
        public Nullable<long> Year { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<decimal> TotalImportedSpareValue { get; set; }
        public Nullable<decimal> TotalGivenHandsetValue { get; set; }
        public Nullable<decimal> SpecialAmount { get; set; }
        public string SpecialRemarks { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> Added { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> Updated { get; set; }
    }
}
