//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterSchedule
    {
        public MasterSchedule()
        {
            this.ArchivedScheduleDetails = new HashSet<ArchivedScheduleDetail>();
            this.ScheduleDetails = new HashSet<ScheduleDetail>();
        }
    
        public long ID { get; set; }
        public long PhaseID { get; set; }
        public string Title { get; set; }
        public Nullable<long> ProjectID { get; set; }
        public Nullable<System.Guid> Product { get; set; }
        public string ProjectModel { get; set; }
        public string ProjectVarientName { get; set; }
        public Nullable<int> TotalOrderQuantity { get; set; }
        public Nullable<int> ScheduleStatus { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<long> AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
    
        public virtual ICollection<ArchivedScheduleDetail> ArchivedScheduleDetails { get; set; }
        public virtual Phase Phase { get; set; }
        public virtual ICollection<ScheduleDetail> ScheduleDetails { get; set; }
    }
}
