//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialWastageItem
    {
        public long Id { get; set; }
        public string ItemCode { get; set; }
        public string ItemDetail { get; set; }
        public double BomUnit { get; set; }
        public Nullable<double> WastagePercentage { get; set; }
        public int AssemblyMaterialFault { get; set; }
        public int AssemblyProcessFault { get; set; }
        public int RepairMaterialFault { get; set; }
        public int RepairProcessFault { get; set; }
        public int TotalWastageFault { get; set; }
        public string BOMType { get; set; }
        public string MonthName { get; set; }
        public int MonthNumber { get; set; }
        public int YearNumber { get; set; }
        public System.DateTime AddedDate { get; set; }
        public long AddedBy { get; set; }
        public long MaterialWastageMasterId { get; set; }
        public Nullable<long> BOMTypeId { get; set; }
    
        public virtual MaterialWastageMaster MaterialWastageMaster { get; set; }
    }
}
