//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialWastageRecommendation
    {
        public long Id { get; set; }
        public long MaterialWastageMasterId { get; set; }
        public string Remarks { get; set; }
        public string RecommendedBy { get; set; }
        public string RecommendationType { get; set; }
        public System.DateTime AddedDate { get; set; }
        public long AddedBy { get; set; }
        public string UserType { get; set; }
    
        public virtual MaterialWastageMaster MaterialWastageMaster { get; set; }
    }
}
