//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialWastageMaster
    {
        public MaterialWastageMaster()
        {
            this.MaterialWastageDetails = new HashSet<MaterialWastageDetail>();
            this.MaterialWastageRecommendations = new HashSet<MaterialWastageRecommendation>();
            this.MaterialWastageItems = new HashSet<MaterialWastageItem>();
        }
    
        public long Id { get; set; }
        public long ProjectOrderQuantityDetailsId { get; set; }
        public string ReportName { get; set; }
        public int MonthNumber { get; set; }
        public string MonthName { get; set; }
        public int YearNumber { get; set; }
        public Nullable<bool> IsInchargeApproved { get; set; }
        public Nullable<long> InchargeId { get; set; }
        public Nullable<bool> IsCooApproved { get; set; }
        public Nullable<long> CooId { get; set; }
        public Nullable<bool> IsSpecialApproved { get; set; }
        public Nullable<long> SpecialApproverId { get; set; }
        public Nullable<bool> IsManagementApproved { get; set; }
        public Nullable<long> ManagementId { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public Nullable<long> CompletedBy { get; set; }
        public System.DateTime AddedDate { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<bool> IsDeputyCooApproved { get; set; }
        public Nullable<long> DeputyCooId { get; set; }
    
        public virtual ICollection<MaterialWastageDetail> MaterialWastageDetails { get; set; }
        public virtual ICollection<MaterialWastageRecommendation> MaterialWastageRecommendations { get; set; }
        public virtual ICollection<MaterialWastageItem> MaterialWastageItems { get; set; }
    }
}
