//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MkMarketOrderQuantityDetail
    {
        public long Id { get; set; }
        public Nullable<long> MkProjectSpecId { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public string PoName { get; set; }
        public Nullable<long> NOC_Quantity { get; set; }
        public Nullable<long> OrderQuantity { get; set; }
        public Nullable<long> FOB_Price { get; set; }
        public string FOB_PriceCurrencyType { get; set; }
        public Nullable<long> BTRC_NOC_Price { get; set; }
        public string BTRC_NOC_PriceCurrencyType { get; set; }
        public Nullable<long> CustomsAssessmentPrice { get; set; }
        public string CustAssPriceCurrencyType { get; set; }
        public Nullable<long> AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
