//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Model
    {
        public System.DateTime RegistrationDate { get; set; }
        public string DealerName { get; set; }
        public string DealerCode { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string Model1 { get; set; }
        public string DealerType { get; set; }
        public string City { get; set; }
        public string Division { get; set; }
    }
}
