//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelWiseLock
    {
        public long Id { get; set; }
        public string Model { get; set; }
        public string OrderNo { get; set; }
        public Nullable<System.DateTime> InventroyAddedDate { get; set; }
        public Nullable<long> OrderQuantity { get; set; }
        public Nullable<int> ActivationThreshold { get; set; }
        public Nullable<bool> IsLock { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
    }
}
