//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelAnalysi
    {
        public int ModelAnalysisId { get; set; }
        public string BrandName { get; set; }
        public string ModelName { get; set; }
        public string PriceUSD { get; set; }
        public string PriceBDT { get; set; }
        public string DisplaySizeIn { get; set; }
        public string DisplayResolution { get; set; }
        public string RAMGB { get; set; }
        public string ROMGB { get; set; }
        public string BatteryMAH { get; set; }
        public string DisplayType { get; set; }
        public string CPUCore { get; set; }
        public string CPUSpeedGHz { get; set; }
        public string CPUMaker { get; set; }
        public string DisplayRatio { get; set; }
        public string BCameraMP { get; set; }
        public string FCameraMP { get; set; }
        public string Thickness { get; set; }
        public string FCamera2ndMP { get; set; }
        public string BCamera2ndMP { get; set; }
        public string DateOfRelease { get; set; }
        public string Fingerprint { get; set; }
        public string FaceRecognition { get; set; }
        public string NetworkG { get; set; }
        public string BodyMaterial { get; set; }
        public string URL { get; set; }
        public string PowerAppsId { get; set; }
    }
}
