//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelWiseServiceQuantityInDay
    {
        public long ModelWiseDaysIds { get; set; }
        public string Model { get; set; }
        public Nullable<long> Tendays { get; set; }
        public Nullable<long> Twentydays { get; set; }
        public Nullable<long> Fortydays { get; set; }
        public Nullable<long> Sixtydays { get; set; }
        public Nullable<long> Nintydays { get; set; }
        public Nullable<long> OneEightydays { get; set; }
        public Nullable<long> Twoseventy { get; set; }
        public Nullable<long> ThreeSixtyFive { get; set; }
        public Nullable<long> RestoftheDays { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string AddedBy { get; set; }
    }
}
