//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MRPEntities : DbContext
    {
        public MRPEntities()
            : base("name=MRPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ArchivedScheduleDetail> ArchivedScheduleDetails { get; set; }
        public virtual DbSet<BomProductModel> BomProductModels { get; set; }
        public virtual DbSet<BOM> BOMs { get; set; }
        public virtual DbSet<DailyProductionCapacity> DailyProductionCapacities { get; set; }
        public virtual DbSet<DailyScheduleDetail> DailyScheduleDetails { get; set; }
        public virtual DbSet<MasterSchedule> MasterSchedules { get; set; }
        public virtual DbSet<Phase> Phases { get; set; }
        public virtual DbSet<PipelineStage> PipelineStages { get; set; }
        public virtual DbSet<ProductType> ProductTypes { get; set; }
        public virtual DbSet<SafetyLevel> SafetyLevels { get; set; }
        public virtual DbSet<ScheduleDetail> ScheduleDetails { get; set; }
        public virtual DbSet<StockCategory> StockCategories { get; set; }
        public virtual DbSet<TimeLinePhase> TimeLinePhases { get; set; }
        public virtual DbSet<TimeLineTaskLog> TimeLineTaskLogs { get; set; }
        public virtual DbSet<UOM> UOMs { get; set; }
        public virtual DbSet<WaltonOffDay> WaltonOffDays { get; set; }
    }
}
