//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NonGradedImeiInventory
    {
        public long Id { get; set; }
        public string Barcode { get; set; }
        public string Imei_One { get; set; }
        public string Imei_Two { get; set; }
        public string Model { get; set; }
        public string Type { get; set; }
        public string Color { get; set; }
        public string OrderNo { get; set; }
        public string Issue { get; set; }
        public string Grade { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
    }
}
