//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OracleLcDetail
    {
        public long Id { get; set; }
        public string ORGANIZATION_NAME { get; set; }
        public string BANK_NAME { get; set; }
        public string LC_CATEGORY { get; set; }
        public string LC_TYPE { get; set; }
        public string SUPPLIER_NAME { get; set; }
        public Nullable<decimal> LC_VALUE { get; set; }
        public string CURRENCY { get; set; }
        public Nullable<decimal> RATE { get; set; }
        public string LC_NUMBER { get; set; }
        public Nullable<decimal> BDT_LC_AMOUNT { get; set; }
        public Nullable<System.DateTime> LC_OPENING_DATE { get; set; }
        public string STATUS { get; set; }
        public string INSURANCE_COMPANY_NAME { get; set; }
        public string PO_NUMBER { get; set; }
        public Nullable<decimal> TOTAL_SHIPMENT_AMOUNT { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
