//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oracle_Material_REC_DATE_With_PO_NO
    {
        public long Id { get; set; }
        public Nullable<long> ProjectMasterId { get; set; }
        public Nullable<long> PurchaseOrderId { get; set; }
        public string OraclePoNo { get; set; }
        public string OracleMaterialReceiveDate { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
    }
}
