//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phase
    {
        public Phase()
        {
            this.MasterSchedules = new HashSet<MasterSchedule>();
        }
    
        public long ID { get; set; }
        public string PhaseName { get; set; }
        public Nullable<int> StartMonthNumber { get; set; }
        public string StartMonth { get; set; }
        public Nullable<int> EndMonthNumber { get; set; }
        public string EndMonth { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual ICollection<MasterSchedule> MasterSchedules { get; set; }
    }
}
