//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhSensorAndOther
    {
        public long PhSensorAndOthersInfoId { get; set; }
        public long ProjectMasterId { get; set; }
        public bool Gsensor { get; set; }
        public bool Psensor { get; set; }
        public bool Lsensor { get; set; }
        public bool Compass { get; set; }
        public bool Gyroscope { get; set; }
        public bool HallSensor { get; set; }
        public bool Otg { get; set; }
        public bool Gps { get; set; }
        public string SpecialSensor { get; set; }
        public Nullable<long> Added { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> Updated { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ProjectMaster ProjectMaster { get; set; }
    }
}
