//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlazaSalesAndActivationRate
    {
        public long Id { get; set; }
        public string Model { get; set; }
        public string PhoneType { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public Nullable<int> PlazaSaleQty { get; set; }
        public Nullable<int> Activation { get; set; }
        public Nullable<decimal> SuccessRate { get; set; }
        public Nullable<decimal> ErrorRate { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
    }
}
