//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pm_Incentive_Base
    {
        public long Id { get; set; }
        public string IncentiveName { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<long> ActiveRole { get; set; }
    }
}
