//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PmAndQcLsdToVesselData
    {
        public long Id { get; set; }
        public Nullable<long> ProjectMasterId { get; set; }
        public string ProjectModel { get; set; }
        public string EmployeeCode { get; set; }
        public string UserFullName { get; set; }
        public Nullable<long> UserId { get; set; }
        public string Orders { get; set; }
        public string ProjectType { get; set; }
        public Nullable<System.DateTime> PoDate { get; set; }
        public Nullable<System.DateTime> LSD { get; set; }
        public Nullable<int> PoVsLSDDiff { get; set; }
        public Nullable<System.DateTime> VesselDate { get; set; }
        public Nullable<int> LsdVsVesselDiffForDeduct { get; set; }
        public Nullable<long> DeductPoint { get; set; }
        public Nullable<long> DeductedAmount { get; set; }
        public Nullable<int> LsdVsVesselDiffForReward { get; set; }
        public Nullable<long> RewardPoint { get; set; }
        public Nullable<long> RewardAmount { get; set; }
        public string RoleName { get; set; }
        public string Month { get; set; }
        public Nullable<int> MonNum { get; set; }
        public Nullable<long> Year { get; set; }
        public Nullable<long> Added { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> Updated { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
