//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PmChinaQcInspectionsClearance
    {
        public long Id { get; set; }
        public Nullable<long> ProjectMasterId { get; set; }
        public string ProjectName { get; set; }
        public string Orders { get; set; }
        public Nullable<long> LotQuantity { get; set; }
        public Nullable<System.DateTime> InspectionStartDate { get; set; }
        public string MaterialType { get; set; }
        public Nullable<int> LotNo { get; set; }
        public Nullable<int> NoOfTimeOfInspection { get; set; }
        public string InspectionAttachment { get; set; }
        public string InspectionStatus { get; set; }
        public string ClearanceStatus { get; set; }
        public string DeniedReason { get; set; }
        public Nullable<long> Added { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> Updated { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
