//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PmChinaQcInspectionsClearanceMailList
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string EmployeeCode { get; set; }
        public string RoleDetails { get; set; }
        public string RoleName { get; set; }
        public string Email { get; set; }
        public string ToMail { get; set; }
        public string FromMail { get; set; }
        public string CcMail { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> RoleNo { get; set; }
        public Nullable<long> Added { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> Updated { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
