//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PmOrderQuantityWithColor
    {
        public long PmOrderQuantityWithColorId { get; set; }
        public long ProjectMasterId { get; set; }
        public string ProjectName { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public string Color { get; set; }
        public long PmOrderQuantity { get; set; }
        public string ConcernPmComment { get; set; }
        public Nullable<long> AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> InventoryReceivedQuantity { get; set; }
        public Nullable<long> InventoryReceivedAddedBy { get; set; }
        public Nullable<System.DateTime> InventoryReceivedDate { get; set; }
        public Nullable<long> CompleteProductionQuantity { get; set; }
        public Nullable<long> CompletedQuantityAddedBy { get; set; }
        public Nullable<System.DateTime> CompletedQuantityAddedDate { get; set; }
        public Nullable<long> WarehouseReceivedQuantity { get; set; }
        public Nullable<long> WarehouseQuantityAddedBy { get; set; }
        public Nullable<System.DateTime> WarehouseQuantityAddedDate { get; set; }
        public Nullable<long> ServiceCenterQuantity { get; set; }
        public Nullable<long> ServiceCenterQuantityAddedBy { get; set; }
        public Nullable<System.DateTime> ServiceCenterQuantityAddedDate { get; set; }
        public string ProductionTeamComment { get; set; }
    }
}
