//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PmOtaUpdate
    {
        public long PmOtaUpdateId { get; set; }
        public long ProjectMasterId { get; set; }
        public long ProjectManagerUserId { get; set; }
        public string RunningOtaSWVersion { get; set; }
        public Nullable<bool> IsForCustomerSatisfaction { get; set; }
        public Nullable<bool> IsMarketIssue { get; set; }
        public Nullable<bool> IsExistingMinorIssue { get; set; }
        public Nullable<System.DateTime> OtaUpdateStartDate { get; set; }
        public Nullable<System.DateTime> OtaUpdateEndDate { get; set; }
        public Nullable<System.DateTime> OtaUpdatePublishDate { get; set; }
        public string OtaUpdateLog { get; set; }
        public Nullable<bool> IsPmHeadApprove { get; set; }
        public string PmHeadRemarks { get; set; }
        public string CurrentOtaSwVersion { get; set; }
        public Nullable<System.DateTime> BinaryFileRequestDate { get; set; }
        public Nullable<bool> IsSoftwareTested { get; set; }
        public Nullable<bool> IsHardwareTested { get; set; }
        public Nullable<bool> IsOtaUploadToServer { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    }
}
