//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PmProjectCompletedTaskLog
    {
        public long PmTabId { get; set; }
        public Nullable<long> ProjectMasterId { get; set; }
        public Nullable<long> ProjectPmAssignId { get; set; }
        public Nullable<long> ProjectManagerUserId { get; set; }
        public Nullable<long> AssignUserId { get; set; }
        public string PmCategoryName { get; set; }
        public Nullable<long> Added { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
    }
}
