//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PmWalpapersLog
    {
        public long PmWalpaperLogId { get; set; }
        public long PmWalpaperId { get; set; }
        public long ProjectAssignId { get; set; }
        public long ProjectMasterId { get; set; }
        public string WalpaperUpload1 { get; set; }
        public string WalpaperUpload2 { get; set; }
        public string WalpaperUpload3 { get; set; }
        public string WalpaperUpload4 { get; set; }
        public string WalpaperUpload5 { get; set; }
        public string WalpaperUpload6 { get; set; }
        public string WalpaperUpload7 { get; set; }
        public string Remarks { get; set; }
        public Nullable<long> Added { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> Updated { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
