//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostComment
    {
        public long PostCommentId { get; set; }
        public Nullable<long> SwQcAllProjectIssueId { get; set; }
        public string Message { get; set; }
        public Nullable<long> CommentedBy { get; set; }
        public Nullable<System.DateTime> CommentedDate { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<long> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
    }
}
