//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pro_MaterialRules
    {
        public long MaterialRulesId { get; set; }
        public string Product { get; set; }
        public string ProductionUnit { get; set; }
        public string TypeOfWork { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> SerialNo { get; set; }
        public Nullable<int> ProductionUnitSerialNo { get; set; }
        public string MaterialRules { get; set; }
        public Nullable<int> StartDays { get; set; }
        public Nullable<int> EndDays { get; set; }
        public Nullable<int> Day_1 { get; set; }
        public Nullable<int> Day_2 { get; set; }
        public Nullable<int> Day_3 { get; set; }
        public Nullable<int> Day_4 { get; set; }
        public Nullable<int> Day_5 { get; set; }
        public Nullable<int> Day_6 { get; set; }
        public Nullable<int> Day_7 { get; set; }
        public Nullable<int> Day_8 { get; set; }
        public Nullable<int> Day_9 { get; set; }
        public Nullable<int> Day_10 { get; set; }
        public Nullable<int> Day_11 { get; set; }
        public Nullable<int> Day_12 { get; set; }
        public Nullable<long> Added { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> Updated { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
