//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projects1
    {
        public long Id { get; set; }
        public string ModelName { get; set; }
        public string Type { get; set; }
        public string SupplierName { get; set; }
        public string SupplierModel { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string Status { get; set; }
    }
}
