//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectCriticalControlPoint
    {
        public long ProjectCriticalControlPointId { get; set; }
        public long ProjectMasterId { get; set; }
        public string Earphone { get; set; }
        public string Charger { get; set; }
        public string Battery { get; set; }
        public string BackCoverMaterial { get; set; }
        public string BackCoverFinishing { get; set; }
        public string LogoPrintType { get; set; }
        public string Flash { get; set; }
        public string OtgCable { get; set; }
        public string FlipCover { get; set; }
        public string ThreeLayerScreenProOnPhone { get; set; }
        public string FreeScreenProOnGb { get; set; }
        public string BackSideScreenPro { get; set; }
        public string BackSideThermalPaper { get; set; }
        public string RawDesignFileOfId { get; set; }
        public string BsiSensor { get; set; }
        public string SarAndCcc { get; set; }
        public string BothSimFourG { get; set; }
        public string UsbCableLength { get; set; }
        public string BackCamera { get; set; }
        public string FronCamera { get; set; }
        public Nullable<long> Added { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> Updated { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
