//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectPoFeedback
    {
        public long Id { get; set; }
        public Nullable<long> ProjectId { get; set; }
        public string ProjectModel { get; set; }
        public string OrderNumber { get; set; }
        public string OnBehalfOf { get; set; }
        public string FeedBack { get; set; }
        public string AllowReorder { get; set; }
        public Nullable<long> AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string FileUploadPath { get; set; }
        public string SourcingComment { get; set; }
        public Nullable<System.DateTime> SourcingCommentDate { get; set; }
        public Nullable<long> SourcingCommentBy { get; set; }
        public string SourcingAllowReorder { get; set; }
        public Nullable<long> ManagementCommentBy { get; set; }
        public string ManagementComment { get; set; }
        public Nullable<System.DateTime> ManagementCommentDate { get; set; }
        public string ManagementDecision { get; set; }
    }
}
