//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectNocDocumentList
    {
        public long ProjectNocDocumentListId { get; set; }
        public long ProjectBrtcNocId { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public long Added { get; set; }
        public System.DateTime AddedDate { get; set; }
        public Nullable<long> Updated { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
