//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectLc
    {
        public long ProjectLcId { get; set; }
        public long ProjectMasterId { get; set; }
        public long ProjectOrderId { get; set; }
        public string LcNo { get; set; }
        public Nullable<System.DateTime> OpeningDate { get; set; }
        public Nullable<System.DateTime> BankOpeningDate { get; set; }
        public Nullable<System.DateTime> SupplierDraftDate { get; set; }
        public Nullable<System.DateTime> LcPassDate { get; set; }
        public Nullable<System.DateTime> SampleSendDate { get; set; }
        public Nullable<System.DateTime> BtrcNocDate { get; set; }
        public Nullable<System.DateTime> NocReceiveDate { get; set; }
        public Nullable<decimal> LcValue { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> BdtLcAmount { get; set; }
        public Nullable<bool> IsComplete { get; set; }
        public Nullable<long> Added { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> Updated { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
