//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectOrderProblemDetail
    {
        public long Id { get; set; }
        public Nullable<long> ProjectMasterId { get; set; }
        public string Model { get; set; }
        public string Orders { get; set; }
        public Nullable<System.DateTime> LaunchDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string ProblemName { get; set; }
        public string SubCategory { get; set; }
        public Nullable<int> SubCategoryQuantity { get; set; }
        public Nullable<int> Activated { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public string Added { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
    }
}
