//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectBtrcNoc
    {
        public long ProjectBtrcNocId { get; set; }
        public long ProjectMasterId { get; set; }
        public Nullable<long> BtrcRawId { get; set; }
        public long ProjectPurchaseOrderFormId { get; set; }
        public long ProjectAssignId { get; set; }
        public string FinalSampleImei { get; set; }
        public Nullable<bool> IsDocUploaded { get; set; }
        public Nullable<bool> IsNocComplete { get; set; }
        public Nullable<long> Added { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> Updated { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string SampleImeiFromBtrcCommercial { get; set; }
        public Nullable<decimal> QuantityFromBtrcCommercial { get; set; }
    }
}
