//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectOrder
    {
        public ProjectOrder()
        {
            this.ProjectOrderConditions = new HashSet<ProjectOrderCondition>();
        }
    
        public long ProjectOrderId { get; set; }
        public long ProjectMasterId { get; set; }
        public string PoNo { get; set; }
        public System.DateTime PoDate { get; set; }
        public long OrderQuantity { get; set; }
        public Nullable<long> Added { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> Updated { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ProjectMaster ProjectMaster { get; set; }
        public virtual ICollection<ProjectOrderCondition> ProjectOrderConditions { get; set; }
    }
}
