//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawMaterialInspection
    {
        public long RawMaterialId { get; set; }
        public Nullable<long> ProjectMasterId { get; set; }
        public Nullable<long> ProjectPurchaseOrderFormId { get; set; }
        public string ProjectName { get; set; }
        public string ProjectType { get; set; }
        public Nullable<int> Orders { get; set; }
        public string PoCategory { get; set; }
        public Nullable<long> PoQuantity { get; set; }
        public Nullable<int> LotNumber { get; set; }
        public Nullable<long> LotQuantity { get; set; }
        public Nullable<System.DateTime> ProjectManagerClearanceDate { get; set; }
        public Nullable<System.DateTime> InspectionStartingDate { get; set; }
        public string MajorDelayReason { get; set; }
        public string ChinaIqcPassHundredPercent { get; set; }
        public Nullable<int> NoOfTimeInspection { get; set; }
        public string ManagementApproval { get; set; }
        public Nullable<System.DateTime> ManagementApprovalDate { get; set; }
        public string HardwareSampleReceive { get; set; }
        public string InspectionMajorFailItems { get; set; }
        public string SourcingApproval { get; set; }
        public string SupportingDocument { get; set; }
        public string InspectionRemarks { get; set; }
        public string OrderColorRatioWithQty { get; set; }
        public Nullable<long> Added { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> Updated { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
