//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesForecastingReport
    {
        public long Id { get; set; }
        public string Model { get; set; }
        public Nullable<long> TotalStock { get; set; }
        public Nullable<long> TotalActivatedInThirtyDays { get; set; }
        public Nullable<long> AverageInThirtyDays { get; set; }
        public Nullable<long> AverageInSevenDays { get; set; }
        public Nullable<long> TotalActivation { get; set; }
        public Nullable<long> TotalDays { get; set; }
        public Nullable<long> LifeTimeAvgActivation { get; set; }
        public Nullable<long> RemainingQuantity { get; set; }
        public Nullable<decimal> AppxStockFinishIn_30_Days { get; set; }
        public Nullable<decimal> AppxStockFinishIn_7_Days { get; set; }
        public Nullable<decimal> Deviation { get; set; }
        public Nullable<System.DateTime> AppxStockFinishDate { get; set; }
        public Nullable<long> PipeLineQuantity { get; set; }
        public Nullable<long> CurrentWarehouseStock { get; set; }
        public Nullable<long> RemainingMarketStock { get; set; }
        public Nullable<decimal> MarketToActivationRatio { get; set; }
        public Nullable<decimal> RemainingToTotalStock { get; set; }
        public string Added { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> TotalPipeLineQuantity { get; set; }
    }
}
