//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SampleTracker
    {
        public long SampleTrackerId { get; set; }
        public Nullable<int> NumberOfSample { get; set; }
        public Nullable<long> ProjectMasterId { get; set; }
        public string Model { get; set; }
        public string SampleSentToDept { get; set; }
        public Nullable<long> SampleSentToPersonId { get; set; }
        public string SampleSentToPersonName { get; set; }
        public string SampleCategory { get; set; }
        public string IMEI { get; set; }
        public string Color { get; set; }
        public string Remarks { get; set; }
        public Nullable<long> AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public Nullable<long> ReceivedBy { get; set; }
        public string ReturnStatus { get; set; }
        public Nullable<long> ReturnedBy { get; set; }
        public Nullable<int> ReturnQuantity { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public string Purpose { get; set; }
        public string SupplierName { get; set; }
        public string Others { get; set; }
        public string AdditionalInfo { get; set; }
        public string SampleIssueTag { get; set; }
        public Nullable<int> SampleIssueQuantity { get; set; }
        public Nullable<long> SampleIssuedBy { get; set; }
        public Nullable<long> SampleIssueReqTo { get; set; }
        public Nullable<System.DateTime> SampleIssueDate { get; set; }
        public string SampleIssuePurpose { get; set; }
        public Nullable<int> InventoryReturnQuantity { get; set; }
        public Nullable<System.DateTime> InventoryReturnDate { get; set; }
        public Nullable<long> InventoryReturnedBy { get; set; }
        public string InventoryReturnRemarks { get; set; }
        public Nullable<System.DateTime> InventoryReceiveDate { get; set; }
        public Nullable<long> InventoryReceivedBy { get; set; }
        public string InventoryReceiveRemarks { get; set; }
    }
}
