//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SatisfactionReplacementHandsetMovement
    {
        public long Id { get; set; }
        public Nullable<long> ServiceID { get; set; }
        public string ServicePointName { get; set; }
        public string IMEI_1 { get; set; }
        public string IMEI_2 { get; set; }
        public string Model { get; set; }
        public string BatchNo { get; set; }
        public string Accessories { get; set; }
        public Nullable<System.DateTime> StoreDeliveredDate { get; set; }
        public Nullable<System.DateTime> StoreReceiveDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsExistsIntoAftersales { get; set; }
        public string Status { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
