//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIMInfo
    {
        public int SIMID { get; set; }
        public string SIMNo { get; set; }
        public string IMSI { get; set; }
        public string OperatorName { get; set; }
        public string ConnetionType { get; set; }
    }
}
