//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSMaster
    {
        public SMSMaster()
        {
            this.SMSDetails = new HashSet<SMSDetail>();
        }
    
        public string SMSID { get; set; }
        public int SLNo { get; set; }
        public string SMSGroup { get; set; }
        public Nullable<System.DateTime> SMSDate { get; set; }
        public string Message { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public string SMSReferance { get; set; }
        public string SMSType { get; set; }
        public Nullable<bool> Unicode { get; set; }
    
        public virtual ICollection<SMSDetail> SMSDetails { get; set; }
    }
}
