//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSRoleMaster
    {
        public SMSRoleMaster()
        {
            this.SMSRoleDetails = new HashSet<SMSRoleDetail>();
        }
    
        public string RoleId { get; set; }
        public Nullable<System.DateTime> RoleDate { get; set; }
        public Nullable<int> RoleNo { get; set; }
        public string RoleName { get; set; }
        public string RoleDescription { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
    
        public virtual ICollection<SMSRoleDetail> SMSRoleDetails { get; set; }
    }
}
