//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SourcingTypeChangingApprovalLog
    {
        public long Id { get; set; }
        public Nullable<long> ProjectMasterId { get; set; }
        public Nullable<long> AcknowledgedBy { get; set; }
        public Nullable<System.DateTime> AcknowledgeDate { get; set; }
        public string AckDeclinedRemarks { get; set; }
        public string AckStatus { get; set; }
        public Nullable<long> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string AppDeclinedRemarks { get; set; }
        public string ApproveStatus { get; set; }
        public Nullable<long> Added { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> Updated { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
