//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpareAnalysisReportMonitor
    {
        public long SpareAnalysisId { get; set; }
        public string ModelName { get; set; }
        public Nullable<long> WarningFor { get; set; }
        public Nullable<bool> IsReportSubmitted { get; set; }
        public Nullable<System.DateTime> ReportSubmitDate { get; set; }
        public Nullable<long> SubmittedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.DateTime> LaunchDate { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public Nullable<long> ReceivedBy { get; set; }
    }
}
