//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecFromApi
    {
        public long Id { get; set; }
        public string RelevantWaltonModelName { get; set; }
        public string ModelName { get; set; }
        public string Brand { get; set; }
        public string Network { get; set; }
        public string DisplayCategory { get; set; }
        public string DisplayType { get; set; }
        public string DisplaySize { get; set; }
        public string Resolution { get; set; }
        public string Processor { get; set; }
        public string Frequency { get; set; }
        public string Core { get; set; }
        public string OperatingSystem { get; set; }
        public string Ram { get; set; }
        public string Rom { get; set; }
        public string DedicatedMicroSdSlot { get; set; }
        public string FrontCamera { get; set; }
        public string RearCamera { get; set; }
        public string CameraLens { get; set; }
        public string Body { get; set; }
        public string VoLte { get; set; }
        public string Otg { get; set; }
        public string Battery { get; set; }
        public string FingerPrint { get; set; }
        public string FaceUnlock { get; set; }
        public string GiftItem { get; set; }
        public string SpecialFeature { get; set; }
        public string MrpPrice { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string DpPrice { get; set; }
        public string RpPrice { get; set; }
        public string BackMargin { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
