//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierRating
    {
        public long SupplierRatingId { get; set; }
        public Nullable<long> SupplierId { get; set; }
        public Nullable<long> ProjectMasterId { get; set; }
        public Nullable<decimal> ShipmentDeliveryPerformance { get; set; }
        public Nullable<decimal> AfterSalesSupport { get; set; }
        public Nullable<decimal> AfterSalesReturn { get; set; }
        public Nullable<decimal> CustomizationSupport { get; set; }
        public string Remarks { get; set; }
        public Nullable<long> Added { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> Updated { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
