//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SwIncentive_AllMembersRewardAndPenalties
    {
        public long Id { get; set; }
        public Nullable<long> ProjectMasterID { get; set; }
        public string ProjectModel { get; set; }
        public string Orders { get; set; }
        public string SourcingType { get; set; }
        public string ShipmentType { get; set; }
        public Nullable<int> TeamMember { get; set; }
        public Nullable<long> RewardAmount { get; set; }
        public Nullable<long> TeamReward { get; set; }
        public Nullable<long> PerPersonReward { get; set; }
        public Nullable<long> DeputyAmount { get; set; }
        public Nullable<long> HeadAmount { get; set; }
        public Nullable<long> DeductedAmount { get; set; }
        public Nullable<long> TeamPenalties { get; set; }
        public Nullable<long> PerPersonPenalties { get; set; }
        public Nullable<long> DeputyPenalties { get; set; }
        public Nullable<long> HeadPenalties { get; set; }
        public Nullable<System.DateTime> WarehouseEntryDate { get; set; }
        public Nullable<System.DateTime> ExtendedWarehouseDate { get; set; }
        public Nullable<System.DateTime> LSD { get; set; }
        public Nullable<System.DateTime> VesselDate { get; set; }
        public Nullable<int> LsdVsVesselDiffForDeduct { get; set; }
        public Nullable<int> LsdVsVesselDiffForReward { get; set; }
        public Nullable<int> EffectiveDays { get; set; }
        public Nullable<long> OrderQuantity { get; set; }
        public Nullable<long> TotalSalesOut { get; set; }
        public Nullable<long> TotalProductionQuantity { get; set; }
        public Nullable<int> ExistedPercentage { get; set; }
        public Nullable<int> MonNum { get; set; }
        public Nullable<long> Year { get; set; }
        public string IncentiveType { get; set; }
        public Nullable<long> Added { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> Updated { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
