//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SwIncentive_PenaltiesForIssues
    {
        public long Id { get; set; }
        public Nullable<long> IssueVerificationId { get; set; }
        public Nullable<long> ProjectMasterId { get; set; }
        public string ModelName { get; set; }
        public string Module { get; set; }
        public string IssueDetails { get; set; }
        public string IssueFrequency { get; set; }
        public string IssueType { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public Nullable<System.DateTime> AddingDate { get; set; }
        public Nullable<System.DateTime> ClosingDate { get; set; }
        public Nullable<System.DateTime> MonthlyStartDate { get; set; }
        public Nullable<System.DateTime> MonthlyEndDate { get; set; }
        public string EmployeeCode { get; set; }
        public Nullable<int> AssignedPersons { get; set; }
        public Nullable<decimal> TotalPenalties { get; set; }
        public Nullable<decimal> ParticularPersonsPenalties { get; set; }
        public Nullable<decimal> FinalAmount { get; set; }
        public string Month { get; set; }
        public Nullable<int> MonNum { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<long> Added { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
    }
}
