//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SwQcHeadAssignsFromPm
    {
        public long SwQcHeadAssignId { get; set; }
        public long ProjectPmAssignId { get; set; }
        public long ProjectMasterId { get; set; }
        public long ProjectOrderShipmentId { get; set; }
        public long ProjectManagerUserId { get; set; }
        public long SwQcHeadUserId { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public string ProjectName { get; set; }
        public string ProjectType { get; set; }
        public System.DateTime PmToQcHeadAssignTime { get; set; }
        public string PmToQcHeadAssignComment { get; set; }
        public Nullable<System.DateTime> PmProjectFinishTime { get; set; }
        public Nullable<System.DateTime> SwQcHeadToQcAssignTime { get; set; }
        public string SwQcHeadToQcAssignComment { get; set; }
        public Nullable<System.DateTime> SwQcFinishedTime { get; set; }
        public Nullable<System.DateTime> SwQcHeadToPmSubmitTime { get; set; }
        public string SwQcHeadToPmForwardComment { get; set; }
        public string AssignCatagory { get; set; }
        public string PriorityFromPm { get; set; }
        public string ProjectManagerSampleType { get; set; }
        public int ProjectManagerSampleNo { get; set; }
        public string SoftwareVersionName { get; set; }
        public Nullable<int> SoftwareVersionNo { get; set; }
        public Nullable<long> TestPhaseID { get; set; }
        public Nullable<bool> IsFinalPhaseMP { get; set; }
        public string Status { get; set; }
        public string SupportingDocument { get; set; }
        public Nullable<bool> IsManagementApproved { get; set; }
        public Nullable<System.DateTime> ManagementApproveDate { get; set; }
        public Nullable<long> Added { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> Updated { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string FieldTestFrom { get; set; }
        public string FieldTestID { get; set; }
        public string AccessoriesTestType { get; set; }
        public string SourceVersion { get; set; }
        public string TargetVersion { get; set; }
    }
}
