//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SwQcEarphoneTest
    {
        public long AccessId { get; set; }
        public Nullable<long> ProjectMasterId { get; set; }
        public Nullable<long> SwQcHeadAssignId { get; set; }
        public Nullable<long> SwQcAssignId { get; set; }
        public Nullable<long> TestPhaseID { get; set; }
        public string ProjectName { get; set; }
        public string ProjectType { get; set; }
        public string HeadphoneModel { get; set; }
        public string MusicPlayerPlayback { get; set; }
        public string VideoPlayerPlayback { get; set; }
        public string VoiceCall { get; set; }
        public string VoiceCallController { get; set; }
        public string FmPlayback { get; set; }
        public string Controller { get; set; }
        public string Remarks { get; set; }
        public string MusicBase { get; set; }
        public string YoutubePlayback { get; set; }
        public string YoutubeController { get; set; }
        public string FmController { get; set; }
        public string VolumeController { get; set; }
        public string HighEndDevice { get; set; }
        public string MidRangeDevice { get; set; }
        public string LowerMidRangeDevice { get; set; }
        public string LowRangeDevice { get; set; }
        public Nullable<long> Added { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> Updated { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
