//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SwQcFieldTestDetail
    {
        public long FieldTestId { get; set; }
        public long SwQcHeadAssignId { get; set; }
        public long SwQcAssignId { get; set; }
        public long ProjectPmAssignId { get; set; }
        public long ProjectMasterId { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public string ProjectName { get; set; }
        public string ProjectType { get; set; }
        public string Issue { get; set; }
        public string ExpectedOutcome { get; set; }
        public string IssueType { get; set; }
        public string IssueAttachment { get; set; }
        public Nullable<long> TestPhaseID { get; set; }
        public string SoftwareVersionName { get; set; }
        public Nullable<int> SoftwareVersionNo { get; set; }
        public string FieldTestFrom { get; set; }
        public string Attachment { get; set; }
        public string BenchmarkPhone { get; set; }
        public string Route { get; set; }
        public string Region { get; set; }
        public string FrequencyBand { get; set; }
        public string FieldTestResult { get; set; }
        public string Remarks { get; set; }
        public string OperatorName { get; set; }
        public string Location { get; set; }
        public string SpeedLimit { get; set; }
        public string TRssiBars { get; set; }
        public string TCallDrop { get; set; }
        public string TNoiseInterference { get; set; }
        public string TLongMute { get; set; }
        public string BRssiBars { get; set; }
        public string BCallDrop { get; set; }
        public string BNoiseInterference { get; set; }
        public string BLongMute { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<long> Added { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> Updated { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
