//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SwQcPersonalUseFindingsIssueDetail
    {
        public long SwQcPrUseFindId { get; set; }
        public long SwQcHeadAssignId { get; set; }
        public long ProjectPmAssignId { get; set; }
        public long ProjectMasterId { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public string ProjectName { get; set; }
        public string ProjectType { get; set; }
        public string IssueScenario { get; set; }
        public string ExpectedOutcome { get; set; }
        public string IssueDetails { get; set; }
        public string RefernceModule { get; set; }
        public string Frequency { get; set; }
        public string IssueReproducePath { get; set; }
        public string Attachment { get; set; }
        public string IssueType { get; set; }
        public string Result { get; set; }
        public Nullable<long> TestPhaseID { get; set; }
        public string SoftwareVersionName { get; set; }
        public Nullable<int> SoftwareVersionNo { get; set; }
        public string FilesUrl { get; set; }
        public string FilesDetail { get; set; }
        public string Upload { get; set; }
        public Nullable<bool> IsFile { get; set; }
        public Nullable<bool> IsIssue { get; set; }
        public Nullable<bool> IsSmart { get; set; }
        public Nullable<bool> IsFeature { get; set; }
        public Nullable<bool> IsWalpad { get; set; }
        public Nullable<bool> IsTab { get; set; }
        public Nullable<bool> IsApprovedForChina { get; set; }
        public Nullable<bool> IsApprovedForIncentive { get; set; }
        public Nullable<bool> IsFinalPhaseMP { get; set; }
        public Nullable<long> Added { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> Updated { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
