//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SwQcAssign
    {
        public long SwQcAssignId { get; set; }
        public Nullable<long> SwQcInchargeAssignId { get; set; }
        public Nullable<long> ProjectPmAssignId { get; set; }
        public long ProjectMasterId { get; set; }
        public Nullable<long> SwQcUserId { get; set; }
        public Nullable<System.DateTime> SwQcAssignTime { get; set; }
        public Nullable<System.DateTime> SwQcReceiveTime { get; set; }
        public Nullable<System.DateTime> SwQcEndTime { get; set; }
        public Nullable<int> QcReceivedSampleNo { get; set; }
        public string QcReceivedImeies { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public string SwInchargeAssignToQcComment { get; set; }
        public string SwQcAssignComment { get; set; }
        public string SwQcEndComment { get; set; }
        public Nullable<System.DateTime> ApproxInchargeToQcDeliveryDate { get; set; }
        public string PriorityFromIncharge { get; set; }
        public string Status { get; set; }
        public string InactiveReasonComment { get; set; }
        public Nullable<long> Added { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> Updated { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.DateTime> QcInchargeToQcReAssignTime { get; set; }
        public Nullable<System.DateTime> QcReAssignProjectFinisedTime { get; set; }
    }
}
