//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SwQcBatteryTest
    {
        public long BatteryId { get; set; }
        public Nullable<long> ProjectMasterId { get; set; }
        public Nullable<long> SwQcHeadAssignId { get; set; }
        public Nullable<long> SwQcAssignId { get; set; }
        public Nullable<long> TestPhaseID { get; set; }
        public string ProjectName { get; set; }
        public string ProjectType { get; set; }
        public string CheckPoints { get; set; }
        public Nullable<int> BatterymAh { get; set; }
        public string HundredToNighty { get; set; }
        public string NightyToEighty { get; set; }
        public string EightyToSeventy { get; set; }
        public string SeventyToSixty { get; set; }
        public string SixtyToFifty { get; set; }
        public string FiftyToFourty { get; set; }
        public string FourtyToThirty { get; set; }
        public string ThirtyToTwenty { get; set; }
        public string TwentyToTen { get; set; }
        public string TenToZero { get; set; }
        public string AverageFullDischarge { get; set; }
        public Nullable<long> Added { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> Updated { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
