//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SwQcAllIncentiveListLog
    {
        public long ListLogId { get; set; }
        public long ListId { get; set; }
        public string ClaimingField { get; set; }
        public string RegularClaimArea { get; set; }
        public string ProjectType { get; set; }
        public Nullable<decimal> Timeline { get; set; }
        public Nullable<decimal> BaseAmount { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<long> Updated { get; set; }
        public Nullable<System.DateTime> Updatedate { get; set; }
        public Nullable<long> Added { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
    }
}
