//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SwQcGlassProtectorTest
    {
        public long Id { get; set; }
        public Nullable<long> ProjectMasterId { get; set; }
        public Nullable<long> SwQcHeadAssignId { get; set; }
        public Nullable<long> SwQcAssignId { get; set; }
        public Nullable<long> TestPhaseID { get; set; }
        public string ProjectName { get; set; }
        public string ProjectType { get; set; }
        public string IssueScenario { get; set; }
        public string ExpectedOutcome { get; set; }
        public string WaltonQcStatus { get; set; }
        public string Upload { get; set; }
        public Nullable<long> IssueSerial { get; set; }
        public Nullable<long> Added { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> Updated { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
