//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCellPhonePricing
    {
        public System.Guid DoNumberId { get; set; }
        public string ProductCode { get; set; }
        public string Model { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> MSDP { get; set; }
        public Nullable<decimal> MSRP { get; set; }
        public string Range { get; set; }
        public string SecondaryRange { get; set; }
        public Nullable<decimal> TotalIncentive { get; set; }
        public Nullable<decimal> DealerIncentive { get; set; }
        public Nullable<decimal> RetailerIncentive { get; set; }
        public Nullable<decimal> SRIncentive { get; set; }
    }
}
