//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCashOut
    {
        public System.Guid CashOutID { get; set; }
        public System.DateTime CashOutDate { get; set; }
        public System.Guid SalesPointID { get; set; }
        public string ReferanceNo { get; set; }
        public System.Guid CashOutHeadID { get; set; }
        public decimal CashOutValue { get; set; }
        public string CurCode { get; set; }
        public string Remark { get; set; }
        public string AddedBy { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual tblSalesPoint tblSalesPoint { get; set; }
        public virtual tblTransectionHead tblTransectionHead { get; set; }
    }
}
