//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDealerInfo
    {
        public System.Guid DealerId { get; set; }
        public string DealerCode { get; set; }
        public string AlternateCode { get; set; }
        public string DealerName { get; set; }
        public string EbsNewServerCode { get; set; }
        public string EbsPartyName { get; set; }
        public string DealerAddress { get; set; }
        public string City { get; set; }
        public string Division { get; set; }
        public string DealerPhoneNumber { get; set; }
        public string AddedBy { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string DealerType { get; set; }
        public string EbsCustomerId { get; set; }
    }
}
