//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLogistic
    {
        public int Id { get; set; }
        public string BoxCode { get; set; }
        public string Imei1 { get; set; }
        public string Imei2 { get; set; }
        public Nullable<long> ProjectId { get; set; }
        public string Color { get; set; }
        public string Model { get; set; }
        public string Grade { get; set; }
        public string GradeReason { get; set; }
        public Nullable<long> AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string Uploaded { get; set; }
        public Nullable<System.DateTime> UploadedDate { get; set; }
        public string OracleUploaded { get; set; }
        public string OracleTransactionCode { get; set; }
        public Nullable<System.DateTime> OracleUploadedDate { get; set; }
        public Nullable<long> OracleUploadedBy { get; set; }
    }
}
