//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductRegistration
    {
        public System.Guid ProductRegID { get; set; }
        public string ProductType { get; set; }
        public System.Guid ProductModelID { get; set; }
        public string SalerID { get; set; }
        public string ProductID { get; set; }
        public string PhoneNumber { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public int WarrantyMonths { get; set; }
        public bool WarrantyVoid { get; set; }
        public string WarrantyID { get; set; }
        public string MemoNo { get; set; }
        public string OwnerName { get; set; }
        public string OwnerAddress { get; set; }
        public string DeliveryDate { get; set; }
        public string EBS_Item_Code { get; set; }
        public string AddedBy { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.Guid> SMSID { get; set; }
        public Nullable<bool> IsSendToOracleDb { get; set; }
        public Nullable<bool> IsCheckedInDealerDistribution { get; set; }
        public string Imei_One { get; set; }
        public string Imei_Tow { get; set; }
    
        public virtual tblProductMaster tblProductMaster { get; set; }
    }
}
