//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductMaster
    {
        public tblProductMaster()
        {
            this.tblDailyClosingStockDetails = new HashSet<tblDailyClosingStockDetail>();
            this.tblProductRegistrations = new HashSet<tblProductRegistration>();
        }
    
        public System.Guid ProductID { get; set; }
        public string ProductCode { get; set; }
        public string ProductType { get; set; }
        public string ProductModel { get; set; }
        public string Category1 { get; set; }
        public string Category2 { get; set; }
        public bool Inactive { get; set; }
        public string AddedBy { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public string OracleModelName { get; set; }
        public string ProductManSource { get; set; }
        public string BrandName { get; set; }
    
        public virtual ICollection<tblDailyClosingStockDetail> tblDailyClosingStockDetails { get; set; }
        public virtual ICollection<tblProductRegistration> tblProductRegistrations { get; set; }
    }
}
