//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSupplierModelInfo
    {
        public long supplierID { get; set; }
        public string supplierName { get; set; }
        public string Model { get; set; }
        public string Type { get; set; }
        public string addedBy { get; set; }
        public Nullable<System.DateTime> addedDate { get; set; }
    }
}
