//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSalesPoint
    {
        public tblSalesPoint()
        {
            this.tblCashIns = new HashSet<tblCashIn>();
            this.tblCashOuts = new HashSet<tblCashOut>();
            this.tblDailyClosingStockDetails = new HashSet<tblDailyClosingStockDetail>();
            this.tblSalesPointDailyStocks = new HashSet<tblSalesPointDailyStock>();
            this.tblSalesPointTransHeads = new HashSet<tblSalesPointTransHead>();
        }
    
        public System.Guid SalesPointID { get; set; }
        public System.Guid CompanyID { get; set; }
        public string SalesPointName { get; set; }
        public string Address { get; set; }
        public bool Inactive { get; set; }
        public string AddedBy { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ICollection<tblCashIn> tblCashIns { get; set; }
        public virtual ICollection<tblCashOut> tblCashOuts { get; set; }
        public virtual tblCompanyInfo tblCompanyInfo { get; set; }
        public virtual ICollection<tblDailyClosingStockDetail> tblDailyClosingStockDetails { get; set; }
        public virtual ICollection<tblSalesPointDailyStock> tblSalesPointDailyStocks { get; set; }
        public virtual ICollection<tblSalesPointTransHead> tblSalesPointTransHeads { get; set; }
    }
}
