//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSMSInbox
    {
        public System.Guid SMSID { get; set; }
        public System.DateTime ReceiveDate { get; set; }
        public string Sender { get; set; }
        public string Message { get; set; }
        public string Status { get; set; }
        public Nullable<int> SMS_Ref { get; set; }
        public Nullable<bool> Processed { get; set; }
        public string GSMGateWayType { get; set; }
        public string AddedBy { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
    }
}
