//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransectionHead
    {
        public tblTransectionHead()
        {
            this.tblCashIns = new HashSet<tblCashIn>();
            this.tblCashOuts = new HashSet<tblCashOut>();
            this.tblSalesPointDailyStocks = new HashSet<tblSalesPointDailyStock>();
            this.tblSalesPointTransHeads = new HashSet<tblSalesPointTransHead>();
        }
    
        public System.Guid TransHeadID { get; set; }
        public string TransHeadName { get; set; }
        public string TransHeadType { get; set; }
        public bool Inactive { get; set; }
        public bool IsProduct { get; set; }
        public string ProductType { get; set; }
        public string AddedBy { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ICollection<tblCashIn> tblCashIns { get; set; }
        public virtual ICollection<tblCashOut> tblCashOuts { get; set; }
        public virtual ICollection<tblSalesPointDailyStock> tblSalesPointDailyStocks { get; set; }
        public virtual ICollection<tblSalesPointTransHead> tblSalesPointTransHeads { get; set; }
    }
}
