//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamKpiPercentageList
    {
        public long Id { get; set; }
        public string KpiName { get; set; }
        public string ProjectType { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<int> Target { get; set; }
        public string ShipmentType { get; set; }
        public Nullable<int> Percentage { get; set; }
        public string RoleName { get; set; }
        public string KpiFor { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<long> Added { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> Updated { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
