//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeTable
    {
        public System.DateTime TIME_ID { get; set; }
        public string DAY_NAM { get; set; }
        public long DAY_NUMBER_IN_WEEK { get; set; }
        public long DAY_NUMBER_IN_MONTH { get; set; }
        public long CALENDAR_WEEK_NUMBER { get; set; }
        public System.DateTime WEEK_ENDING_DAY { get; set; }
        public long CALENDAR_MONTH_NUMBER { get; set; }
        public string CALENDAR_MONTH_DESC { get; set; }
        public long DAYS_IN_CAL_MONTH { get; set; }
        public System.DateTime END_OF_CAL_MONTH { get; set; }
        public string CALENDAR_MONTH_NAME { get; set; }
        public string CALENDAR_QUARTER_DESC { get; set; }
        public long DAYS_IN_CAL_QUARTER { get; set; }
        public System.DateTime END_OF_CAL_QUARTER { get; set; }
        public long CALENDAR_QUARTER_NUMBER { get; set; }
        public long CALENDAR_YEAR { get; set; }
        public long DAYS_IN_CAL_YEAR { get; set; }
        public System.DateTime END_OF_CAL_YEAR { get; set; }
        public string PERIOD_NAME { get; set; }
    }
}
