//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLoginTracker
    {
        public long Id { get; set; }
        public Nullable<long> CmnUserId { get; set; }
        public string UserName { get; set; }
        public string UserFullName { get; set; }
        public Nullable<System.DateTime> LoginDateTime { get; set; }
        public string IpAddress { get; set; }
        public string Role { get; set; }
        public string ExtendedRole { get; set; }
    }
}
