using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ProjectManagement.Models
{
    public class HwTestPcbAModel
    {
        public long HwTestPcbAId { get; set; }
        public Nullable<long> HwQcAssignId { get; set; }
        public Nullable<long> HwQcInchargeAssignId { get; set; }
        public string Chipset_Vendor { get; set; }
        public string IcNoSize { get; set; }
        public string Chipset_Core { get; set; }
        public string Chipset_Speed { get; set; }
        public string Chipset_PinType { get; set; }
        public Nullable<int> Chipset_PinNumber { get; set; }
        public string Chipset_Remark { get; set; }
        public string FlashIC_Vendor { get; set; }
        public string Flash_IcNoSize { get; set; }
        public string FlashIC_Technology { get; set; }
        public string FlashIC_RAM { get; set; }
        public string FlashIC_ROM { get; set; }
        public string FlashIC_Ball { get; set; }
        public string FlashIC_PinType { get; set; }
        public Nullable<int> FlashIC_PinNumber { get; set; }
        public string FlashIC_Remark { get; set; }
        public string RFIC { get; set; }
        public string RFIC_Vendor { get; set; }
        public string RFIC_PinType { get; set; }
        public Nullable<int> RFIC_PinNumber { get; set; }
        public string RFIC_Remark { get; set; }
        public string PMU1IC { get; set; }
        public string PMU1IC_Vendor { get; set; }
        public string PMU1IC_PinType { get; set; }
        public Nullable<int> PMU1IC_PinNumber { get; set; }
        public string PMU1IC_Remark { get; set; }
        public string PMU2IC { get; set; }
        public string PMU2IC_Vendor { get; set; }
        public string PMU2IC_PinType { get; set; }
        public string PMU2IC_PinNumber { get; set; }
        public string PMU2IC_Remark { get; set; }
        public string BT_IcNoSize { get; set; }
        public string BT_Remark { get; set; }
        public string WiFi_IcNoSize { get; set; }
        public string WiFi_Remark { get; set; }
        public string BTWIFIIC { get; set; }
        public string BTWIFIIC_Vendor { get; set; }
        public string BTWIFIIC_PinType { get; set; }
        public Nullable<int> BTWIFIIC_PinNumber { get; set; }
        public string BTWIFIIC_Remark { get; set; }
        public string RFNetwork { get; set; }
        public string RFNetwork_2GPA { get; set; }
        public string RFNetwork_2GPA_Vendor { get; set; }
        public Nullable<int> RFNetwork_2GPA_PinNumber { get; set; }
        public string RFNetwork_2GPA_PinType { get; set; }
        public string RFNetwork_2GPA_Remark { get; set; }
        public string RFNetwork_3GPA { get; set; }
        public string RFNetwork_3GPA_Vendor { get; set; }
        public string RFNetwork_3GPA_PinType { get; set; }
        public Nullable<int> RFNetwork_3GPA_PinNumber { get; set; }
        public string RFNetwork_3GPA_Remark { get; set; }
        public string RFNetwork_4GPA { get; set; }
        public string RFNetwork_4GPA_Vendor { get; set; }
        public Nullable<int> RFNetwork_4GPA_PinNumber { get; set; }
        public string RFNetwork_4GPA_pinType { get; set; }
        public string RFNetwork_4GPA_Remark { get; set; }
        public string RFNetwork_TDD { get; set; }
        public string RFNetwork_CDMAPA { get; set; }
        public string RFNetwork_3G { get; set; }
        public string RFNetwork_TDDPA { get; set; }
        public string RFNetwork_4G { get; set; }
        public string Charging_IC { get; set; }
        public string Charging_IC_Vendor { get; set; }
        public string Charging_IC_PinNumber { get; set; }
        public Nullable<int> Charging_IC_PinType { get; set; }
        public string Charging_IC_Remark { get; set; }
        public string Charging_Switch { get; set; }
        public string Charging_Rating { get; set; }
        public string BacklightIC { get; set; }
        public string BacklightIC_Vendor { get; set; }
        public string BacklightIC_PinNumber { get; set; }
        public Nullable<int> BacklightIC_PinType { get; set; }
        public string BacklightIC_Remark { get; set; }
        public string AudioPA { get; set; }
        public string AudioPA_IcNoSize { get; set; }
        public string AudioPA_Vendor { get; set; }
        public string AudioPA_PinType { get; set; }
        public Nullable<int> AudioPA_PinNumber { get; set; }
        public string AudioPA_Remark { get; set; }
        public bool AudioPA_Yes { get; set; }
        public string AudioPA_No { get; set; }
        public string AudioPA_Class { get; set; }
        public string Sensors_PSensorIC { get; set; }
        public string Sensors_PSensorIC_Remark { get; set; }
        public string Sensors_GSensorIC { get; set; }
        public string Sensors_GSensorIC_Remark { get; set; }
        public string Sensors_MSensorIC { get; set; }
        public string Sensors_MSensorIC_Remark { get; set; }
        public string Sensors_OTG { get; set; }
        public string USBConnector_Name { get; set; }
        public string USBConnector_Type { get; set; }
        public string FlashLightDriver_Name { get; set; }
        public string FlashLightDriver_Original { get; set; }
        public string FlashLightDriver_Fake { get; set; }
        public string SubPCBA { get; set; }
        public string SubPCBA_Name { get; set; }
        public string HandSolderingPoint_Name { get; set; }
        public string HandSolderingPoint_Qty { get; set; }
        public string GPU { get; set; }
        public string Recommendation { get; set; }
        public string Comment { get; set; }
        public string QcDocUploadPath { get; set; }
        public Nullable<long> Added { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> Updated { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string ImageExtension { get; set; }
        public HttpPostedFileBase HwQcDocUpload { get; set; }
    }
}